### # Registration

POST http://localhost:8899/api/v1/auth/registration
Content-Type: application/json

{
  "name":"Alisa",
  "surname":"Tokaev",
  "email":"alisatokaev@gmail.com",
  "password":"123456"
}

### # Verification
GET http://localhost:8899/api/v1/auth/verification/eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGlzYXRva2FldkBnbWFpbC5jb20iLCJpYXQiOjE2NjYwODgyMTQsImV4cCI6MTY2NjE3NDYxNCwiaXNzIjoiVXNlZnVsIENvZGVzIHByb2R1Y3Rpb24ifQ.7qaz1-B0QQVEMLSWjNBNAH3QMYvHIwuKmxx_tZpS8Ac

### # Login
POST http://localhost:8899/api/v1/auth/login
Content-Type: application/json

{
  "email":"alisatokaev@gmail.com",
  "password":"123456"
}