
###
POST http://localhost:8899/api/v1/qrcode/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGlzYXRva2FldkBnbWFpbC5jb20iLCJpYXQiOjE2NjYxNzUwNTksImV4cCI6MTY2NjI2MTQ1OSwiaXNzIjoiVXNlZnVsIENvZGVzIHByb2R1Y3Rpb24ifQ.DEFdx7oXU2s96YzWgERqfFvPhLf-abauVE_RqZ63Q5Q

{
  "colorConfig": {
    "bgColor": "#000000",
    "eye1": {
      "medium": "#000000",
      "outer": "#ffffff",
      "small": "#ffffff"
    },
    "eye2": {
      "medium": "#000000",
      "outer": "#ffffff",
      "small": "#ffffff"
    },
    "eye3": {
      "medium": "#000000",
      "outer": "#ffffff",
      "small": "#ffffff"
    },
    "pointColor": "#ffffff"
  },
  "data": "Assalomu Alaykum",
  "extension": "png",
  "height": 400,
  "logoAttachId": "string",
  "save": true,
  "width": 400
}

###
GET http://localhost:8899/api/v1/qrcode/open-general/32b0487f-5985-48a7-80e3-da56e164ea1c

###
GET http://localhost:8899/api/v1/qrcode/download/32b0487f-5985-48a7-80e3-da56e164ea1c


###
DELETE http://localhost:8899/api/v1/qrcode/delete/9a4c1340-5b7b-4197-acfa-bc6fba6185d0
